### ISSUE TITLE
Update docs to list redcarpet as a dependency?

### ISSUE THREAD

**Issue by himedlooff** [cfpb/DOCter#1]
When running `jekyll serve --baseurl ''` for the first time I got:

```
ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Missing dependency: redcarpet
```

The command line gave me instructions to fix it. I think it was something like `$ gem install redcarpet`. It worked but I wonder if this should be in the docs.

**Comment by ascott1** [comment]
I may just ditch redcarpet. I'm not sure why I'm using it other than that I had it in the _config file of another project. Surely there was a reason at some point, but I think default Jekyll markdown parsing should work fine.

**Comment by ascott1** [comment]
Nevermind... losing it causes some weird issues. I'll add it to the documentation. Thanks!

**Comment by ascott1** [comment]
Added in b6c2840e14214cfbb21e9e2c2369d8de42015a6b

:fireworks:

**Comment by himedlooff** [comment]
What if you switch to kramdown? I had to do this on https://github.com/cfpb/capital-framework to get auto semantic heading id's so that I could link to them.

**Comment by ascott1** [comment]
There was some reason for using redcarpet originally, though I've totally forgotten what it was. Is kramdown working well both locally and on gh-pages?

**Comment by Scotchester** [comment]
The original reason was probably simply to get around the terrible bugs of the default engine, Maruku.

**Comment by himedlooff** [comment]
I couldn't get named-fenced code blocks with syntax highlighting to work with redcarpet or kramdown, but i didn't try that hard. Anyone know anything off the top of their heads about support for that in either?

**Comment by Scotchester** [comment]
Exhibit A:
- https://github.com/cfpb/qu/blob/gh-pages/_config.yml#L2
- https://raw.githubusercontent.com/cfpb/qu/gh-pages/getting-started.md
- http://cfpb.github.io/qu/getting-started.html
