### ISSUE TITLE
Remove references to Avenir Next from CSS

### ISSUE THREAD

**Issue by Scotchester** [cfpb/DOCter#12]
Since we can't include it with the source.

**Comment by ascott1** [comment]
I believe Avenir Next ships with OSX now, so makes sense to use in the font stack. It would probably be safe to fall back to Avenir and then Arial.

So: `"Avenir Next", Avenir, Arial, sans-serif;`

**Comment by Scotchester** [comment]
Hmm... fair enough. I'd just be sure to test it on Windows to make sure that most users don't get an unfortunate overflow or anything weird resulting from falling back to Arial.

I'm not sure I would include standard Avenir, though. The weights are pretty screwy (no equivalents of demi or bold) and don't really match up with Avenir Next.

**Comment by ascott1** [comment]
Already done, thanks for double checking!
