### ISSUE TITLE
Remove unused .repo-list class?

### ISSUE THREAD

**Issue by himedlooff** [cfpb/DOCter#4]
In the CSS there are `.repo-list` styles that are not being used on the demo site. Is it ok to delete them or do you have plans to use them?

**Comment by ascott1** [comment]
Good question... I know it's a nice little design on the eRegs site, but it doesn't feel very flexible to use in a template.

**Comment by Scotchester** [comment]
I think it's cool and could be useful to others. We could get fancy and set it up in the `_config.yml`, a la the navbar, so people wouldn't have to edit the raw HTML.

**Comment by ascott1** [comment]
Good idea @Scotchester
