### ISSUE TITLE
Clearer side nav example?

### ISSUE THREAD

**Issue by himedlooff** [cfpb/DOCter#6]
At first it was confusing that the navigation links on the left did not do anything because they all link to the same page. Maybe you can do something like you did [here](http://eregs.github.io/eregulations/) where the first items are anchor links within the home page and then you can have an example nav item that links to another page like you have already.

**Comment by ascott1** [comment]
Great idea. :+1: I may even just link to an external site or two.

**Comment by ascott1** [comment]
Cool, I just updated it and fixed the 404 issue by adding an `internal: true` or 'false` to the _config file. I may add a second example page if you think it would make things clearer.

**Comment by himedlooff** [comment]
Oh ok. So there was no need for me to add `/` to the links then?

**Comment by ascott1** [comment]
Yeah, I hadn't taken into account he baseurl, so I added an If/else to the template. It feels a little weird, but seems to work well.
