### ISSUE TITLE
Missing logo?

### ISSUE THREAD

**Issue by himedlooff** [cfpb/DOCter#7]
Is there supposed to be a logo image in the header or is it intentionally left without a `src` vlaue?

**Comment by ascott1** [comment]
This is intentional (for now). The logo URL and alt text can be set in the _config file, but this keeps the repo free of PII.

**Comment by himedlooff** [comment]
Ok cool, just checking.

**Comment by himedlooff** [comment]
I'm surprised there is no :pie: emoji.

**Comment by ascott1** [comment]
Man, there should be a pie emoji. We'll have to settle for :cake: I guess
